#!/usr/bin/python
# -*- coding: utf-8 -*-
#
#       edna.py
#       
#       Copyright 2011 Podlesnyj Maxim <edna.filebrowser@yandex.ua>
#       
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.

import __builtin__

__builtin__.edna_builtin = {}

import pygtk
import gtk
from edna_filemanager import load

pygtk.require('2.0')

def main():
    gtk.gdk.threads_init()
    load.load_structures()
    load.load_config()
    load.load_icons_container()
    Edna_Window = load.init_root_window()
    
    gtk.gdk.threads_enter()
    gtk.main()
    gtk.gdk.threads_leave()
    return 0

if __name__ == '__main__':
    main()

